# 08 — Bipartite Optimality Analysis

This notebook studies the special case of bipartite Max-Cut instances with
only non-negative edge weights.

For such graphs, the optimal Max-Cut value is known exactly: assigning the two
bipartition sets to opposite sides of the cut separates every edge. Therefore,
the true optimum is equal to the sum of all edge weights.

The analysis focuses on the following questions:

1. How many benchmark instances satisfy the bipartite and non-negative
   edge-weight conditions, and how are these instances distributed across
   size and density categories?

2. How often do DAv3c, DAv2, DAv3, and the selected MQLib heuristics reach
   the exact optimal Max-Cut value on these instances?

The notebook also examines:

- Solver result availability across the filtered instance set
- The distribution of instances by `size_cat` and `density_cat`
- The MQLib heuristic responsible for each heuristic result
- Exact optimality gaps relative to the known optimum
- Optimality-hit percentages across all evaluated solvers

This analysis provides a correctness-oriented evaluation setting in which the
true optimum is analytically known, allowing solver performance to be assessed
without requiring external reference solutions.

In [1]:
from pathlib import Path
import sys
import numpy as np
import pandas as pd

#project imports
sys.path.append(str(Path("../src/maxcut").resolve()))

%load_ext autoreload
%autoreload 2

import config as cfg
import utils
import plotting

In [2]:
# import paths
PATH_BASELINE_DATASET = cfg.PROCESSED_DIR / 'baseline_dataset.csv'

In [3]:
df_baseline = pd.read_csv(PATH_BASELINE_DATASET)
df_baseline.head()

,name,nodes,edges,density,limit,has_leafs,int_only,size_cat,density_cat,heuristics_name,...,neg_wt_sum,neg_wt_ratio,triangle_count,has_triangles,transitivity,average_clustering,cyclomatic_number,bridge_count,bridge_fraction,unique_weights
0,G55,4969,12498,0.001013,13.945,True,True,large,sparse,BURER2002,...,0.0,0.000000,23,True,0.001100,0.001189,7530,180,0.014402,1
1,G56,4969,12498,0.001013,13.922,True,True,large,sparse,BURER2002,...,-6276.0,0.502160,23,True,0.001100,0.001189,7530,180,0.014402,2
2,G57,5000,10000,0.000800,11.299,False,True,large,sparse,BURER2002,...,-5019.0,0.501900,0,False,0.000000,0.000000,5001,0,0.000000,2
3,G58,5000,29570,0.002366,11.876,False,True,large,sparse,BURER2002,...,0.0,0.000000,30784,True,0.098091,0.326822,24571,0,0.000000,1
4,G59,5000,29570,0.002366,15.875,False,True,large,sparse,BURER2002,...,-14737.0,0.498377,30784,True,0.098091,0.326822,24571,0,0.000000,2

In [4]:
df_baseline = df_baseline[df_baseline['limit']>0.25]

In [5]:
df_final = df_baseline[(df_baseline['bipartite']==True) & (df_baseline['neg_edges']==0)]

In [6]:
(
    df_final["size_cat"]
    .value_counts()
    .reindex(cfg.SIZE_ORDER)
)

size_cat
xsmall    40
small     30
medium    42
large     24
xlarge    10
Name: count, dtype: int64

In [7]:
df_final.loc[df_final['size_cat'] == 'xlarge', 'name']

902     g000775
1019    g000901
1037    g000921
1250    g001146
1289    g001188
1946    g001896
2854    g002877
2921    g002948
2940    g002967
3200    g003234
Name: name, dtype: str

In [8]:
(
    df_final["density_cat"]
    .value_counts()
    .reindex(cfg.DENSITY_ORDER)
)

density_cat
sparse      146.0
balanced      NaN
dense         NaN
Name: count, dtype: float64

In [10]:
df_final[cfg.SOLVERS].notna().sum()

DAv2            136
DAv3            146
DAv3c           146
heuristic       146
BURER2002       146
MERZ1999GLS     146
PAL2004bMTS2    146
dtype: int64

In [11]:
df_final['int_only'].value_counts()

int_only
True     130
False     16
Name: count, dtype: int64

In [12]:
total = len(df_final)
obj_value = []

for i, graph_name in enumerate(df_final['name'], 1):
    progress = (i / total) * 100
    sys.stdout.write(
        f"\rProcessed {i}/{total} "
        f"({progress:.2f}%) | Current: {graph_name}"
    )
    sys.stdout.flush()

    zip_path = utils.find_zip_for_graph(graph_name)
    print(zip_path)
    if zip_path is None:
        print(f'Missing ZIP for {graph_name}')
        continue

    _, edges, *_ = utils.read_edgelist_from_zip(zip_path) 
  
    try:
        _, edges, *_ = utils.read_edgelist_from_zip(zip_path) 
    except Exception:
        continue

    obj_value.append(sum(e[2] for e in edges))

Processed 1/146 (0.68%) | Current: g000006/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000006.zip
Processed 2/146 (1.37%) | Current: g000039/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000039.zip
Processed 3/146 (2.05%) | Current: g000049/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000049.zip
Processed 4/146 (2.74%) | Current: g000062/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000062.zip
Processed 5/146 (3.42%) | Current: g000068/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000068.zip
Processed 6/146 (4.11%) | Current: g000078/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000078.zip
Processed 7/146 (4.79%) | Current: g000101/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000101.zip
Processed 8/146 (5.48%) | Current: g000107/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000107.zip
Processed 9/146 (6.16%) | Current: g000112/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000112.zip
Processed 10/146 (6.85%) | Current: g000180/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000180.zip
Processed 11/146 (7.53%) | Current: g000250/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000250.zip
Processed 12/146 (8.22%) | Current: g000255/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000255.zip
Processed 13/146 (8.90%) | Current: g000267/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000267.zip
Processed 14/146 (9.59%) | Current: g000278/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000278.zip
Processed 15/146 (10.27%) | Current: g000284/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000284.zip
Processed 16/146 (10.96%) | Current: g000317/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000317.zip
Processed 17/146 (11.64%) | Current: g000319/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000319.zip
Processed 18/146 (12.33%) | Current: g000354/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000354.zip
Processed 19/146 (13.01%) | Current: g000379/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000379.zip
Processed 20/146 (13.70%) | Current: g000380/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000380.zip
Processed 21/146 (14.38%) | Current: g000383/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000383.zip
Processed 22/146 (15.07%) | Current: g000436/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000436.zip
Processed 23/146 (15.75%) | Current: g000497/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000497.zip
Processed 24/146 (16.44%) | Current: g000510/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000510.zip
Processed 25/146 (17.12%) | Current: g000529/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000529.zip
Processed 26/146 (17.81%) | Current: g000556/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000556.zip
Processed 27/146 (18.49%) | Current: g000591/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000591.zip
Processed 28/146 (19.18%) | Current: g000610/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000610.zip
Processed 29/146 (19.86%) | Current: g000638/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000638.zip
Processed 30/146 (20.55%) | Current: g000709/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000709.zip
Processed 31/146 (21.23%) | Current: g000721/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000721.zip
Processed 32/146 (21.92%) | Current: g000775/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000775.zip
Processed 33/146 (22.60%) | Current: g000777/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000777.zip
Processed 34/146 (23.29%) | Current: g000785/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000785.zip
Processed 35/146 (23.97%) | Current: g000794/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000794.zip
Processed 36/146 (24.66%) | Current: g000795/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000795.zip
Processed 37/146 (25.34%) | Current: g000811/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000811.zip
Processed 38/146 (26.03%) | Current: g000830/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000830.zip
Processed 39/146 (26.71%) | Current: g000832/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000832.zip
Processed 40/146 (27.40%) | Current: g000899/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000899.zip
Processed 41/146 (28.08%) | Current: g000901/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000901.zip
Processed 42/146 (28.77%) | Current: g000909/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000909.zip
Processed 43/146 (29.45%) | Current: g000921/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000921.zip
Processed 44/146 (30.14%) | Current: g000929/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000929.zip
Processed 45/146 (30.82%) | Current: g000980/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000980.zip
Processed 46/146 (31.51%) | Current: g000989/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g000989.zip
Processed 47/146 (32.19%) | Current: g001004/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001004.zip
Processed 48/146 (32.88%) | Current: g001008/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001008.zip
Processed 49/146 (33.56%) | Current: g001064/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001064.zip
Processed 50/146 (34.25%) | Current: g001135/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001135.zip
Processed 51/146 (34.93%) | Current: g001138/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001138.zip
Processed 52/146 (35.62%) | Current: g001146/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001146.zip
Processed 53/146 (36.30%) | Current: g001160/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001160.zip
Processed 54/146 (36.99%) | Current: g001188/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001188.zip
Processed 55/146 (37.67%) | Current: g001190/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001190.zip
Processed 56/146 (38.36%) | Current: g001228/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001228.zip
Processed 57/146 (39.04%) | Current: g001230/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001230.zip
Processed 58/146 (39.73%) | Current: g001253/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001253.zip
Processed 59/146 (40.41%) | Current: g001256/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001256.zip
Processed 60/146 (41.10%) | Current: g001262/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001262.zip
Processed 61/146 (41.78%) | Current: g001275/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001275.zip
Processed 62/146 (42.47%) | Current: g001366/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001366.zip
Processed 63/146 (43.15%) | Current: g001372/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001372.zip
Processed 64/146 (43.84%) | Current: g001428/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001428.zip
Processed 65/146 (44.52%) | Current: g001571/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001571.zip
Processed 66/146 (45.21%) | Current: g001582/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001582.zip
Processed 67/146 (45.89%) | Current: g001591/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001591.zip
Processed 68/146 (46.58%) | Current: g001601/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001601.zip
Processed 69/146 (47.26%) | Current: g001620/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001620.zip
Processed 70/146 (47.95%) | Current: g001622/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001622.zip
Processed 71/146 (48.63%) | Current: g001623/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001623.zip
Processed 72/146 (49.32%) | Current: g001636/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001636.zip
Processed 73/146 (50.00%) | Current: g001669/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001669.zip
Processed 74/146 (50.68%) | Current: g001675/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001675.zip
Processed 75/146 (51.37%) | Current: g001680/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001680.zip
Processed 76/146 (52.05%) | Current: g001686/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001686.zip
Processed 77/146 (52.74%) | Current: g001687/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001687.zip
Processed 78/146 (53.42%) | Current: g001722/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001722.zip
Processed 79/146 (54.11%) | Current: g001765/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001765.zip
Processed 80/146 (54.79%) | Current: g001785/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001785.zip
Processed 81/146 (55.48%) | Current: g001799/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001799.zip
Processed 82/146 (56.16%) | Current: g001804/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001804.zip
Processed 83/146 (56.85%) | Current: g001808/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001808.zip
Processed 84/146 (57.53%) | Current: g001817/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001817.zip
Processed 85/146 (58.22%) | Current: g001865/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001865.zip
Processed 86/146 (58.90%) | Current: g001893/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001893.zip
Processed 87/146 (59.59%) | Current: g001895/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001895.zip
Processed 88/146 (60.27%) | Current: g001896/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001896.zip
Processed 89/146 (60.96%) | Current: g001911/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001911.zip
Processed 90/146 (61.64%) | Current: g001918/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001918.zip
Processed 91/146 (62.33%) | Current: g001928/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001928.zip
Processed 92/146 (63.01%) | Current: g001936/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001936.zip
Processed 93/146 (63.70%) | Current: g001943/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001943.zip
Processed 94/146 (64.38%) | Current: g001966/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001966.zip
Processed 95/146 (65.07%) | Current: g001988/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g001988.zip
Processed 96/146 (65.75%) | Current: g002021/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002021.zip
Processed 97/146 (66.44%) | Current: g002090/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002090.zip
Processed 98/146 (67.12%) | Current: g002094/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002094.zip
Processed 99/146 (67.81%) | Current: g002147/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002147.zip
Processed 100/146 (68.49%) | Current: g002163/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002163.zip
Processed 101/146 (69.18%) | Current: g002183/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002183.zip
Processed 102/146 (69.86%) | Current: g002231/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002231.zip
Processed 103/146 (70.55%) | Current: g002242/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002242.zip
Processed 104/146 (71.23%) | Current: g002250/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002250.zip
Processed 105/146 (71.92%) | Current: g002257/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002257.zip
Processed 106/146 (72.60%) | Current: g002307/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002307.zip
Processed 107/146 (73.29%) | Current: g002315/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002315.zip
Processed 108/146 (73.97%) | Current: g002372/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002372.zip
Processed 109/146 (74.66%) | Current: g002391/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002391.zip
Processed 110/146 (75.34%) | Current: g002452/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002452.zip
Processed 111/146 (76.03%) | Current: g002467/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002467.zip
Processed 112/146 (76.71%) | Current: g002486/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002486.zip
Processed 113/146 (77.40%) | Current: g002522/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002522.zip
Processed 114/146 (78.08%) | Current: g002535/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002535.zip
Processed 115/146 (78.77%) | Current: g002561/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002561.zip
Processed 116/146 (79.45%) | Current: g002607/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002607.zip
Processed 117/146 (80.14%) | Current: g002616/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002616.zip
Processed 118/146 (80.82%) | Current: g002629/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002629.zip
Processed 119/146 (81.51%) | Current: g002682/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002682.zip
Processed 120/146 (82.19%) | Current: g002686/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002686.zip
Processed 121/146 (82.88%) | Current: g002734/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002734.zip
Processed 122/146 (83.56%) | Current: g002767/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002767.zip
Processed 123/146 (84.25%) | Current: g002781/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002781.zip
Processed 124/146 (84.93%) | Current: g002789/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002789.zip
Processed 125/146 (85.62%) | Current: g002804/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002804.zip
Processed 126/146 (86.30%) | Current: g002815/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002815.zip
Processed 127/146 (86.99%) | Current: g002844/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002844.zip
Processed 128/146 (87.67%) | Current: g002845/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002845.zip
Processed 129/146 (88.36%) | Current: g002877/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002877.zip
Processed 130/146 (89.04%) | Current: g002900/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002900.zip
Processed 131/146 (89.73%) | Current: g002948/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002948.zip
Processed 132/146 (90.41%) | Current: g002967/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002967.zip
Processed 133/146 (91.10%) | Current: g002979/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g002979.zip
Processed 134/146 (91.78%) | Current: g003020/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003020.zip
Processed 135/146 (92.47%) | Current: g003025/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003025.zip
Processed 136/146 (93.15%) | Current: g003026/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003026.zip
Processed 137/146 (93.84%) | Current: g003031/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003031.zip
Processed 138/146 (94.52%) | Current: g003042/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003042.zip
Processed 139/146 (95.21%) | Current: g003095/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003095.zip
Processed 140/146 (95.89%) | Current: g003119/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003119.zip
Processed 141/146 (96.58%) | Current: g003121/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003121.zip
Processed 142/146 (97.26%) | Current: g003131/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003131.zip
Processed 143/146 (97.95%) | Current: g003213/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003213.zip
Processed 144/146 (98.63%) | Current: g003234/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003234.zip
Processed 145/146 (99.32%) | Current: g003249/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003249.zip
Processed 146/146 (100.00%) | Current: g003251/Users/sargun/Desktop/DAMB-DAv3c/data/raw/mqlib_instances/g003251.zip

In [13]:
len(obj_value)

146

In [15]:
df_final['Objective Value'] = obj_value

In [16]:
df_final.columns

Index(['name', 'nodes', 'edges', 'density', 'limit', 'has_leafs', 'int_only',
       'size_cat', 'density_cat', 'heuristics_name', 'DAv2', 'DAv2_runtime',
       'DAv3', 'DAv3_runtime', 'DAv3c', 'DAv3c_runtime', 'BURER2002',
       'BURER2002_runtime', 'MERZ1999GLS', 'MERZ1999GLS_runtime',
       'PAL2004bMTS2', 'PAL2004bMTS2_runtime', 'heuristic',
       'heuristic_runtime', 'baseline_objective', 'best_solvers', 'bipartite',
       'neg_edges', 'neg_edges_frac', 'neg_wt_sum', 'neg_wt_ratio',
       'triangle_count', 'has_triangles', 'transitivity', 'average_clustering',
       'cyclomatic_number', 'bridge_count', 'bridge_fraction',
       'unique_weights', 'Objective Value'],
      dtype='str')

In [17]:
import numpy as np
import pandas as pd

solvers = [
    "DAv2",
    "DAv3",
    "DAv3c",
    "BURER2002",
    "MERZ1999GLS",
    "PAL2004bMTS2"
]

opt_col = "Objective Value"
baseline_col = "baseline_objective"
EPS = 1e-9

# Use the same instances for all six solvers
required_cols = solvers + [opt_col, baseline_col]

common_df = df_final.dropna(subset=required_cols).copy()

print("Common instances:", len(common_df))

# Verify the stored six-solver baseline
common_df["best_of_six_check"] = common_df[solvers].max(axis=1)

baseline_matches = np.isclose(
    common_df[baseline_col],
    common_df["best_of_six_check"],
    atol=EPS,
    rtol=0
)

print("Baseline mismatches:", (~baseline_matches).sum())

# Verify that no solver exceeds the certified optimum
above_optimum = (
    common_df[solvers].gt(
        common_df[opt_col] + EPS,
        axis=0
    )
)

print("Solver values exceeding optimum:", above_optimum.sum().sum())

assert baseline_matches.all(), "Stored baseline differs from best of six"
assert not above_optimum.any().any(), "Some solver values exceed the optimum"

rows = []

for solver in solvers:

    values = common_df[solver].to_numpy(float)
    optimum = common_df[opt_col].to_numpy(float)
    baseline = common_df[baseline_col].to_numpy(float)

    # Relative success: best among six
    relative_success = np.isclose(
        values, baseline,
        atol=EPS,
        rtol=0
    )

    # Exact recovery: matches known optimum
    exact_recovery = np.isclose(
        values, optimum,
        atol=EPS,
        rtol=0
    )

    # Absolute optimality gap in objective units
    absolute_gap = optimum - values

    # Relative optimality gap (%), defined when optimum > 0
    relative_gap = np.where(
        optimum > 0,
        100 * absolute_gap / np.where(optimum > 0, optimum, 1),
        np.nan
    )

    rows.append({
        "solver": solver,
        "N": len(common_df),

        "relative_success_n": int(relative_success.sum()),
        "relative_success_pct": 100 * relative_success.mean(),

        "exact_recovery_n": int(exact_recovery.sum()),
        "exact_recovery_pct": 100 * exact_recovery.mean(),

        "median_optimality_gap_pct": np.nanmedian(relative_gap),
        "mean_optimality_gap_pct": np.nanmean(relative_gap),

        "max_optimality_gap_pct": np.nanmax(relative_gap)
    })

opt_df = pd.DataFrame(rows)

display(opt_df.round(4))

Common instances: 136
Baseline mismatches: 0
Solver values exceeding optimum: 0

,solver,N,relative_success_n,relative_success_pct,exact_recovery_n,exact_recovery_pct,median_optimality_gap_pct,mean_optimality_gap_pct,max_optimality_gap_pct
0,DAv2,136,125,91.9118,125,91.9118,0.0000,0.0237,0.8159
1,DAv3,136,133,97.7941,131,96.3235,0.0000,0.0228,2.3651
2,DAv3c,136,101,74.2647,100,73.5294,0.0000,0.1961,1.9374
3,BURER2002,136,101,74.2647,101,74.2647,0.0000,0.2080,1.4081
4,MERZ1999GLS,136,49,36.0294,49,36.0294,0.9628,1.0361,2.6636
5,PAL2004bMTS2,136,56,41.1765,55,40.4412,0.8096,0.8599,3.3800

In [18]:
# Does at least one of the six solvers recover the true optimum?
best_six_optimal = np.isclose(
    common_df["best_of_six_check"],
    common_df[opt_col],
    atol=EPS,
    rtol=0
)

print("Total instances:", len(common_df))
print("Best-of-six recovers optimum:", best_six_optimal.sum())
print("Best-of-six recovery rate (%):", 100 * best_six_optimal.mean())

print(
    "Instances where all six solvers miss the optimum:",
    (~best_six_optimal).sum()
)

display(
    common_df.loc[
        ~best_six_optimal,
        ["name", opt_col, baseline_col] + solvers
    ]
)

Total instances: 136
Best-of-six recovers optimum: 132
Best-of-six recovery rate (%): 97.05882352941177
Instances where all six solvers miss the optimum: 4

,name,Objective Value,baseline_objective,DAv2,DAv3,DAv3c,BURER2002,MERZ1999GLS,PAL2004bMTS2
1103,g000989,2322.000000,2319.000000,2318.000000,2319.000000,2300.000000,2299.000000,2283.000000,2288.000000
2009,g001966,1465.000000,1464.000000,1462.000000,1464.000000,1453.000000,1453.000000,1436.000000,1440.000000
2175,g002147,61065.170469,61055.337667,60566.921113,61019.943519,60984.720606,60991.783050,61040.520753,61055.337667
2210,g002183,51109.374690,51109.374690,50791.779036,50874.118650,51109.374690,50438.894976,50274.215748,50344.792560

In [19]:
quality_rows = []

for solver in solvers:

    values = common_df[solver].to_numpy(float)
    optimum = common_df[opt_col].to_numpy(float)
    baseline = common_df[baseline_col].to_numpy(float)

    relative_success = np.isclose(
        values, baseline,
        atol=EPS,
        rtol=0
    )

    exact_recovery = np.isclose(
        values, optimum,
        atol=EPS,
        rtol=0
    )

    gap_pct = np.where(
        optimum > 0,
        100 * (optimum - values) / np.where(optimum > 0, optimum, 1),
        np.nan
    )

    for status, mask in [
        ("Relative success", relative_success),
        ("Relative failure", ~relative_success)
    ]:
        selected_gaps = gap_pct[mask]

        quality_rows.append({
            "solver": solver,
            "relative_status": status,
            "N": int(mask.sum()),
            "exact_recovery_n": int(exact_recovery[mask].sum()),
            "exact_recovery_pct": (
                100 * exact_recovery[mask].mean()
                if mask.sum() > 0 else np.nan
            ),
            "median_gap_pct": (
                np.nanmedian(selected_gaps)
                if mask.sum() > 0 else np.nan
            ),
            "mean_gap_pct": (
                np.nanmean(selected_gaps)
                if mask.sum() > 0 else np.nan
            ),
            "p90_gap_pct": (
                np.nanpercentile(selected_gaps, 90)
                if mask.sum() > 0 else np.nan
            )
        })

quality_df = pd.DataFrame(quality_rows)

display(quality_df.round(4))

,solver,relative_status,N,exact_recovery_n,exact_recovery_pct,median_gap_pct,mean_gap_pct,p90_gap_pct
0,DAv2,Relative success,125,125,100.0000,0.0000,0.0000,0.0000
1,DAv2,Relative failure,11,0,0.0000,0.1926,0.2932,0.6214
2,DAv3,Relative success,133,131,98.4962,0.0000,0.0015,0.0000
3,DAv3,Relative failure,3,0,0.0000,0.4603,0.9665,1.9842
4,DAv3c,Relative success,101,100,99.0099,0.0000,0.0000,0.0000
5,DAv3c,Relative failure,35,0,0.0000,0.8191,0.7621,1.2072
6,BURER2002,Relative success,101,101,100.0000,0.0000,0.0000,0.0000
7,BURER2002,Relative failure,35,0,0.0000,0.8445,0.8081,1.2690
8,MERZ1999GLS,Relative success,49,49,100.0000,0.0000,0.0000,0.0000
9,MERZ1999GLS,Relative failure,87,0,0.0000,1.6174,1.6196,2.4589
10,PAL2004bMTS2,Relative success,56,55,98.2143,0.0000,0.0003,0.0000
11,PAL2004bMTS2,Relative failure,80,0,0.0000,1.3832,1.4616,2.2984

In [20]:
EPS = 1e-9

common_df["best_of_six_optimal"] = np.isclose(
    common_df["baseline_objective"],
    common_df["Objective Value"],
    atol=EPS,
    rtol=0
)

missed_df = common_df.loc[
    ~common_df["best_of_six_optimal"]
].copy()

print("Total instances:", len(common_df))
print(
    "At least one solver recovered the optimum:",
    common_df["best_of_six_optimal"].sum()
)
print(
    "No solver recovered the optimum:",
    len(missed_df)
)

display(
    missed_df[
        ["name", "Objective Value", "baseline_objective"]
        + solvers
    ]
)

Total instances: 136
At least one solver recovered the optimum: 132
No solver recovered the optimum: 4

,name,Objective Value,baseline_objective,DAv2,DAv3,DAv3c,BURER2002,MERZ1999GLS,PAL2004bMTS2
1103,g000989,2322.000000,2319.000000,2318.000000,2319.000000,2300.000000,2299.000000,2283.000000,2288.000000
2009,g001966,1465.000000,1464.000000,1462.000000,1464.000000,1453.000000,1453.000000,1436.000000,1440.000000
2175,g002147,61065.170469,61055.337667,60566.921113,61019.943519,60984.720606,60991.783050,61040.520753,61055.337667
2210,g002183,51109.374690,51109.374690,50791.779036,50874.118650,51109.374690,50438.894976,50274.215748,50344.792560

In [21]:
import numpy as np
import pandas as pd

EPS = 1e-9

missed_check = missed_df.copy()

missed_check["absolute_gap"] = (
    missed_check["Objective Value"]
    - missed_check["baseline_objective"]
)

missed_check["relative_gap_pct"] = (
    100 * missed_check["absolute_gap"]
    / missed_check["Objective Value"]
)

missed_check["isclose_abs_1e9"] = np.isclose(
    missed_check["Objective Value"],
    missed_check["baseline_objective"],
    atol=1e-9,
    rtol=0
)

# Diagnostic only: a scale-aware tolerance
missed_check["isclose_rel_1e10"] = np.isclose(
    missed_check["Objective Value"],
    missed_check["baseline_objective"],
    atol=1e-9,
    rtol=1e-10
)

with pd.option_context("display.precision", 15):
    display(
        missed_check[
            [
                "name",
                "Objective Value",
                "baseline_objective",
                "absolute_gap",
                "relative_gap_pct",
                "isclose_abs_1e9",
                "isclose_rel_1e10"
            ]
        ]
    )

,name,Objective Value,baseline_objective,absolute_gap,relative_gap_pct,isclose_abs_1e9,isclose_rel_1e10
1103,g000989,2322.000000000000000,2319.000000000000000,3.000000000000000,0.129198966408269,False,False
2009,g001966,1465.000000000000000,1464.000000000000000,1.000000000000000,0.068259385665529,False,False
2175,g002147,61065.170469061384210,61055.337666508588882,9.832802552795329,0.016102145424743,False,False
2210,g002183,51109.374690000004193,51109.374689997173846,0.000000002830348,0.000000000005538,False,True

In [22]:
rows = []

for _, row in missed_df.iterrows():

    best = row["baseline_objective"]
    optimum = row["Objective Value"]

    relative_winners = [
        s for s in solvers
        if np.isclose(row[s], best, atol=EPS, rtol=0)
    ]

    rows.append({
        "name": row["name"],
        "absolute_gap": optimum - best,
        "relative_winners": ", ".join(relative_winners)
    })

display(pd.DataFrame(rows))

      name  absolute_gap relative_winners
0  g000989  3.000000e+00             DAv3
1  g001966  1.000000e+00             DAv3
2  g002147  9.832803e+00     PAL2004bMTS2
3  g002183  2.830348e-09            DAv3c

In [23]:
ATOL = 1e-9
RTOL = 1e-10

rows = []

for solver in solvers:
    recovered = np.isclose(
        common_df[solver].to_numpy(float),
        common_df["Objective Value"].to_numpy(float),
        atol=ATOL,
        rtol=RTOL
    )

    rows.append({
        "solver": solver,
        "N": len(common_df),
        "exact_recovery_n": int(recovered.sum()),
        "exact_recovery_pct": 100 * recovered.mean()
    })

recovery_df = pd.DataFrame(rows)
display(recovery_df.round(4))

         solver    N  exact_recovery_n  exact_recovery_pct
0          DAv2  136               125             91.9118
1          DAv3  136               131             96.3235
2         DAv3c  136               101             74.2647
3     BURER2002  136               101             74.2647
4   MERZ1999GLS  136                49             36.0294
5  PAL2004bMTS2  136                55             40.4412

In [31]:
for solver in solvers:

    valid = df_final[[solver, "Objective Value", "size_cat"]].dropna()

    failed = valid[
    ~np.isclose(
        valid[solver],
        valid["Objective Value"],
        atol=1e-9,
        rtol=0
    )
]

    print(f"\n===== {solver} failures by size =====")

    print(
        failed["size_cat"]
        .value_counts()
        .reindex(cfg.SIZE_ORDER)
    )

===== DAv2 failures by size =====
size_cat
xsmall    NaN
small     1.0
medium    6.0
large     4.0
xlarge    NaN
Name: count, dtype: float64

===== DAv3 failures by size =====
size_cat
xsmall     1
small      1
medium     2
large      1
xlarge    10
Name: count, dtype: int64

===== DAv3c failures by size =====
size_cat
xsmall     1
small      4
medium    16
large     15
xlarge     6
Name: count, dtype: int64

===== BURER2002 failures by size =====
size_cat
xsmall     NaN
small      1.0
medium    18.0
large     16.0
xlarge    10.0
Name: count, dtype: float64

===== MERZ1999GLS failures by size =====
size_cat
xsmall    20
small     18
medium    31
large     18
xlarge    10
Name: count, dtype: int64

===== PAL2004bMTS2 failures by size =====
size_cat
xsmall    22
small     18
medium    24
large     17
xlarge    10
Name: count, dtype: int64

In [26]:
# Select medium and large instances
df_66 = common_df.loc[
    common_df["size_cat"].isin(["medium", "large"])
].copy()

print("Total instances:", len(df_66))
print("\nSize distribution:")
print(df_66["size_cat"].value_counts())

assert len(df_66) == 66, (
    f"Expected 66 instances, found {len(df_66)}"
)

assert df_66[solvers + ["Objective Value", "baseline_objective"]].notna().all().all()

Total instances: 66

Size distribution:
size_cat
medium    42
large     24
Name: count, dtype: int64

In [27]:
import numpy as np
import pandas as pd

EPS = 1e-9

def evaluate_known_optima(df, solvers, eps=1e-9):
    rows = []

    # Recompute and verify the best of six
    best_of_six = df[solvers].max(axis=1).to_numpy(float)
    optimum = df["Objective Value"].to_numpy(float)

    stored_baseline = df["baseline_objective"].to_numpy(float)

    assert np.isclose(
        best_of_six, stored_baseline,
        atol=eps, rtol=0
    ).all(), "Mismatch in stored six-solver baseline"

    assert np.all(optimum > 0), (
        "Relative gap requires positive optimum values"
    )

    assert np.all(best_of_six <= optimum + eps), (
        "Best-of-six objective exceeds the known optimum"
    )

    for solver in solvers:
        values = df[solver].to_numpy(float)

        relative_success = np.isclose(
            values, best_of_six,
            atol=eps, rtol=0
        )

        exact_recovery = np.isclose(
            values, optimum,
            atol=eps, rtol=0
        )

        gap_pct = 100 * (optimum - values) / optimum

        rows.append({
            "Solver": solver,
            "N": len(df),
            "Relative_success_n": int(relative_success.sum()),
            "Relative_success_%": 100 * relative_success.mean(),
            "Exact_recovery_n": int(exact_recovery.sum()),
            "Exact_recovery_%": 100 * exact_recovery.mean(),
            "Mean_gap_%": gap_pct.mean(),
            "Median_gap_%": np.median(gap_pct),
            "Max_gap_%": gap_pct.max()
        })

    return pd.DataFrame(rows)

results_136 = evaluate_known_optima(common_df, solvers)
results_66 = evaluate_known_optima(df_66, solvers)

print("=== FULL KNOWN-OPTIMUM SUBSET (N=136) ===")
display(results_136.round(4))

print("=== MEDIUM/LARGE SENSITIVITY SUBSET (N=66) ===")
display(results_66.round(4))

=== FULL KNOWN-OPTIMUM SUBSET (N=136) ===

,Solver,N,Relative_success_n,Relative_success_%,Exact_recovery_n,Exact_recovery_%,Mean_gap_%,Median_gap_%,Max_gap_%
0,DAv2,136,125,91.9118,125,91.9118,0.0237,0.0000,0.8159
1,DAv3,136,133,97.7941,131,96.3235,0.0228,0.0000,2.3651
2,DAv3c,136,101,74.2647,100,73.5294,0.1961,0.0000,1.9374
3,BURER2002,136,101,74.2647,101,74.2647,0.2080,0.0000,1.4081
4,MERZ1999GLS,136,49,36.0294,49,36.0294,1.0361,0.9628,2.6636
5,PAL2004bMTS2,136,56,41.1765,55,40.4412,0.8599,0.8096,3.3800

=== MEDIUM/LARGE SENSITIVITY SUBSET (N=66) ===

,Solver,N,Relative_success_n,Relative_success_%,Exact_recovery_n,Exact_recovery_%,Mean_gap_%,Median_gap_%,Max_gap_%
0,DAv2,66,56,84.8485,56,84.8485,0.0458,0.0000,0.8159
1,DAv3,66,64,96.9697,63,95.4545,0.0101,0.0000,0.4603
2,DAv3c,66,36,54.5455,35,53.0303,0.3381,0.0000,1.5420
3,BURER2002,66,32,48.4848,32,48.4848,0.4161,0.1225,1.4081
4,MERZ1999GLS,66,17,25.7576,17,25.7576,1.3771,1.5557,2.6636
5,PAL2004bMTS2,66,26,39.3939,25,37.8788,1.0136,0.9442,2.6534

In [28]:
comparison = results_136.merge(
    results_66,
    on="Solver",
    suffixes=("_136", "_66"),
    validate="one_to_one"
)

comparison["Recovery_change_pp"] = (
    comparison["Exact_recovery_%_66"]
    - comparison["Exact_recovery_%_136"]
)

comparison["Relative_success_change_pp"] = (
    comparison["Relative_success_%_66"]
    - comparison["Relative_success_%_136"]
)

display(
    comparison[
        [
            "Solver",
            "Relative_success_%_136",
            "Relative_success_%_66",
            "Exact_recovery_%_136",
            "Exact_recovery_%_66",
            "Recovery_change_pp",
            "Mean_gap_%_136",
            "Mean_gap_%_66"
        ]
    ].round(3)
)

,Solver,Relative_success_%_136,Relative_success_%_66,Exact_recovery_%_136,Exact_recovery_%_66,Recovery_change_pp,Mean_gap_%_136,Mean_gap_%_66
0,DAv2,91.912,84.848,91.912,84.848,-7.063,0.024,0.046
1,DAv3,97.794,96.970,96.324,95.455,-0.869,0.023,0.010
2,DAv3c,74.265,54.545,73.529,53.030,-20.499,0.196,0.338
3,BURER2002,74.265,48.485,74.265,48.485,-25.780,0.208,0.416
4,MERZ1999GLS,36.029,25.758,36.029,25.758,-10.272,1.036,1.377
5,PAL2004bMTS2,41.176,39.394,40.441,37.879,-2.562,0.860,1.014

In [29]:
for label, df in [
    ("All common instances", common_df),
    ("Medium/Large only", df_66)
]:
    optimum = df["Objective Value"].to_numpy(float)
    best_of_six = df[solvers].max(axis=1).to_numpy(float)

    recovered = np.isclose(
        best_of_six,
        optimum,
        atol=EPS,
        rtol=0
    )

    print(f"\n{label}")
    print("N:", len(df))
    print("Best-of-six recovered:", int(recovered.sum()))
    print("Recovery rate (%):", round(100 * recovered.mean(), 2))

    print("Instances not recovered:")
    display(
        df.loc[
            ~recovered,
            ["name", "size_cat", "Objective Value",
             "baseline_objective"]
        ]
    )

All common instances
N: 136
Best-of-six recovered: 132
Recovery rate (%): 97.06
Instances not recovered:

         name size_cat  Objective Value  baseline_objective
1103  g000989   medium      2322.000000         2319.000000
2009  g001966    small      1465.000000         1464.000000
2175  g002147    large     61065.170469        61055.337667
2210  g002183   medium     51109.374690        51109.374690

Medium/Large only
N: 66
Best-of-six recovered: 63
Recovery rate (%): 95.45
Instances not recovered:

         name size_cat  Objective Value  baseline_objective
1103  g000989   medium      2322.000000         2319.000000
2175  g002147    large     61065.170469        61055.337667
2210  g002183   medium     51109.374690        51109.374690

In [30]:
print("Minimum time limit:", df_66["limit"].min())

print(
    "Instances with original time limit below 1 second:",
    int((df_66["limit"] < 1).sum())
)

Minimum time limit: 2.609
Instances with original time limit below 1 second: 0